---
- name: Create ZooKeeper install path
  file: state=directory path={{zookeeper_install_path}}

- name: Download ZooKeeper
  get_url: url={{zookeeper_download_url}} dest={{zookeeper_archive}}

- name: Unpack ZooKeeper archive
  unarchive: src={{zookeeper_archive}} dest={{zookeeper_install_path}} copy=no creates={{zookeeper_home}}

- name: Set symlink for ZooKeeper cfg file
  file: state=link path={{zookeeper_cfg}} src={{zookeeper_sample_cfg}}

- name: Fix ownership
  file: state=directory path={{deploy_home}} owner={{user_name}} group={{user_group}} recurse=yes

- name: Add ZooKeeper supervisor file
  template: src=zoo.conf dest="{{zoo_supervisor_file}}" owner="{{user_name}}" group={{user_group}}

- name: Start the ZooKeeper service
  supervisorctl: >
    name=zookeeper
    config={{ supervisor_file }}
    state=restarted
