---
- hosts: jnz
  remote_user: "{{user_name}}"
  vars:
    jar_file: "{{jstorm_modifiled_server_jar}}"
    client_jar_file: "{{jstorm_modifiled_client_jar}}"
  roles:
    - jstormcopy

- hosts: jsupervisor
  remote_user: "{{user_name}}"
  vars:
    jar_file: "{{jstorm_modifiled_server_jar}}"
    client_jar_file: "{{jstorm_modifiled_client_jar}}"
  roles:
    - jstormcopy