---
- hosts: jnz
  remote_user: "{{user_name}}"
  roles:
  - zookeeper
- hosts: jnz
  remote_user: "{{user_name}}"
  roles:
  - jnimbus
- hosts: jsupervisor
  remote_user: "{{user_name}}"
  roles:
  - jsupervisor
- hosts: rabbitmq
  remote_user: "{{user_name}}"
  roles:
  - rabbitmq