---
- hosts: nz
  remote_user: "{{user_name}}"
  roles:
  - zookeeper
- hosts: nz
  remote_user: "{{user_name}}"
  roles:
  - nimbus
- hosts: supervisor
  remote_user: "{{user_name}}"
  roles:
  - supervisor