---
- name: Create Storm install path
  file: state=directory path={{storm_install_path}}

- name: Download Storm
  get_url: url={{storm_download_url}} dest={{storm_archive}}

- name: Unpack Storm archive
  unarchive: src={{storm_archive}} dest={{storm_install_path}} copy=no creates={{storm_home}}

- name: Add Nimbus conf file
  template: src=storm.yaml dest="{{storm_cfg}}" owner="{{user_name}}" group={{user_group}}

- name: Fix ownership
  file: state=directory path={{deploy_home}} owner={{user_name}} group={{user_group}} recurse=yes

- name: Add Nimbus supervisor file
  template: src=nimbus.conf dest="{{storm_nimbus_supervisor_file}}" owner="{{user_name}}" group={{user_group}}

- name: Start the Storm Nimbus service
  supervisorctl: >
    name=nimbus
    config={{ supervisor_file }}
    state=restarted

- name: Add Storm UI supervisor file
  template: src=ui.conf dest="{{storm_ui_supervisor_file}}" owner="{{user_name}}" group={{user_group}}

- name: Start the Storm Nimbus service
  supervisorctl: >
    name=ui
    config={{ supervisor_file }}
    state=restarted