---
- name: Install libselinux-python
  yum: name=libselinux-python state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install unzip
  apt: name=unzip state=latest

- name: Add the entries to hosts file
  sudo: yes
  command: cat hosts >> /etc/hosts

- name: Install git
  apt: name=git state=latest

- name: Create supervisor conf path
  file: state=directory path={{supervisor_dir}} owner={{user_name}} group={{user_group}}

- name: Create Java install path
  file: state=directory path={{java_install_path}} owner={{user_name}} group={{user_group}}

- name: Download Oracle Java 7
  command: "wget -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{java_download_url}} creates={{java_archive}}"

- name: Unpack Java archive
  command: "tar zxf {{java_archive}} -C {{java_install_path}} creates={{java_name}}"

- name: Fix ownership
  file: state=directory path={{java_name}} owner="{{user_name}}" group={{user_group}} recurse=yes

- name: Set symlink for latest Java
  file: state=link path={{java_symlink}} src={{java_name}}

- name: Set symlink for default Java
  file: state=link path={{java_default}} src={{java_symlink}}

- name: Install python setup tools
  sudo: yes
  apt: name=python-setuptools state=latest

- name: Install Supervisord
  sudo: yes
  apt: name=supervisor state=latest